config/routes.rb
Xpd3::Application.routes.draw do
  
  resources :external_accounts

  resources :suppliers

  resources :ipfixes

  get "pages/directions"

  resources :cmdlines

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  root :to => 'pages#home'
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]  #qualifieing it like this means '/sessions/1' doesn't work, neither does '/sessions/1/edit'
  resources :relationships, :only => [:create, :destroy]
  resources :people, :only => [:create, :destroy, :index]
  
  resources :news_blasts
  
  match '/manage', :to => 'pages#manage'
  match '/about', :to => 'pages#about'
  match '/gallery', :to => 'pages#gallery'
  match '/specials', :to => 'pages#specials'
  match '/products', :to => 'pages#products'
  match '/news', :to => 'pages#news'
  match '/directions', :to => 'pages#directions'
  
  match "/brendan", :to => 'pages#brendan'
  
  match '/template', :to => 'pages#template'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/employees/new', :to => 'employees#new'
  
  resources :employees

end

app/models/ipfix.rb
class Ipfix < ActiveRecord::Base
  attr_accessible :host, :ip
  
  validates :host, :uniqueness => true
end

app/controllers/ipfixes_controller.rb
class IpfixesController < ApplicationController
  # GET /ipfixes
  # GET /ipfixes.xml
  def index
    @ipfixes = Ipfix.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ipfixes }
    end
  end

  # GET /ipfixes/1
  # GET /ipfixes/1.xml
  def show
    @ipfix = Ipfix.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ipfix }
    end
  end

  # GET /ipfixes/new
  # GET /ipfixes/new.xml
  def new
    @ipfix = Ipfix.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ipfix }
    end
  end

  # GET /ipfixes/1/edit
  def edit
    @ipfix = Ipfix.find(params[:id])
  end

  # POST /ipfixes
  # POST /ipfixes.xml
  def create
    @already_existing_host = Ipfix.where(:host => params[:ipfix][:host])
    
      puts "HERE:"
      p params
      puts 
      
      # Check if host exists, if so
    if @already_existing_host.empty?
      @ipfix = Ipfix.new(params[:ipfix])
        
      respond_to do |format|
        if @ipfix.save
          format.html { redirect_to(@ipfix, :notice => 'Ipfix was successfully created.') }
          format.xml  { render :xml => @ipfix, :status => :created, :location => @ipfix }
          format.json { render :json => @ipfix, :status => :ok, :location => @ipfix }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @ipfix.errors, :status => :unprocessable_entity }
          format.json  { render :json => @ipfix.errors, :status => :unprocessable_entity }
        end
      end
      
    else
      @already_existing_host = @already_existing_host.first
      
      @already_existing_host.ip = params[:ipfix][:ip]
      respond_to do |format|
        if @already_existing_host.save
          format.html { redirect_to(@already_existing_host, :notice => 'Ipfix was successfully updated.') }
          format.xml  { render :xml => @already_existing_host, :status => :created, :location => @already_existing_host }
          format.json { render :json => @already_existing_host, :status => :ok, :location => @already_existing_host }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @already_existing_host, :status => :unprocessable_entity }
          format.json  { render :json => @already_existing_host, :status => :unprocessable_entity }
        end
      end
    end
    
  end

  # PUT /ipfixes/1
  # PUT /ipfixes/1.xml
  def update
    @ipfix = Ipfix.find(params[:id])

    respond_to do |format|
      if @ipfix.update_attributes(params[:ipfix])
        format.html { redirect_to(@ipfix, :notice => 'Ipfix was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ipfix.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ipfixes/1
  # DELETE /ipfixes/1.xml
  def destroy
    @ipfix = Ipfix.find(params[:id])
    @ipfix.destroy

    respond_to do |format|
      format.html { redirect_to(ipfixes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ipfixes_helper.rb
module IpfixesHelper
end

app/views/ipfixes/_form.html.erb
<%= form_for(@ipfix) do |f| %>
  <% if @ipfix.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ipfix.errors.count, "error") %> prohibited this ipfix from being saved:</h2>

      <ul>
      <% @ipfix.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :host %><br />
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ipfixes/edit.html.erb
<h1>Editing ipfix</h1>

<%= render 'form' %>

<%= link_to 'Show', @ipfix %> |
<%= link_to 'Back', ipfixes_path %>

app/views/ipfixes/index.html.erb
<h1>Listing ipfixes</h1>
HellOOOOO

<table>
  <tr>
    <th>Host</th>
    <th>Ip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ipfixes.each do |ipfix| %>
  <tr>
    <td><%= ipfix.host %></td>
    <td><%= ipfix.ip %></td>
    <td><%= link_to 'Show', ipfix %></td>
    <td><%= link_to 'Edit', edit_ipfix_path(ipfix) %></td>
    <td><%= link_to 'Destroy', ipfix, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ipfix', new_ipfix_path %>

app/views/ipfixes/new.html.erb
<h1>New ipfix</h1>

<%= render 'form' %>

<%= link_to 'Back', ipfixes_path %>

app/views/ipfixes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Host:</b>
  <%= @ipfix.host %>
</p>

<p>
  <b>Ip:</b>
  <%= @ipfix.ip %>
</p>


<%= link_to 'Edit', edit_ipfix_path(@ipfix) %> |
<%= link_to 'Back', ipfixes_path %>