config/routes.rb
Xpd3::Application.routes.draw do
  
  resources :external_accounts

  resources :suppliers

  resources :ipfixes

  get "pages/directions"

  resources :cmdlines

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  root :to => 'pages#home'
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]  #qualifieing it like this means '/sessions/1' doesn't work, neither does '/sessions/1/edit'
  resources :relationships, :only => [:create, :destroy]
  resources :people, :only => [:create, :destroy, :index]
  
  resources :news_blasts
  
  match '/manage', :to => 'pages#manage'
  match '/about', :to => 'pages#about'
  match '/gallery', :to => 'pages#gallery'
  match '/specials', :to => 'pages#specials'
  match '/products', :to => 'pages#products'
  match '/news', :to => 'pages#news'
  match '/directions', :to => 'pages#directions'
  
  match "/brendan", :to => 'pages#brendan'
  
  match '/template', :to => 'pages#template'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/employees/new', :to => 'employees#new'
  
  resources :employees

end

app/models/news_blast.rb
class NewsBlast < ActiveRecord::Base
  attr_accessible :date, :headline, :content
  
  validates_presence_of :date, :headline, :content
  #serialize :content
end

app/controllers/news_blasts_controller.rb
class NewsBlastsController < ApplicationController
  before_filter :admin_user, :only => [:create, :destroy, :index]
  
  # GET /news_blasts
  # GET /news_blasts.xml
  def index
    @news_blasts = NewsBlast.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news_blasts }
    end
  end

  # GET /news_blasts/1
  # GET /news_blasts/1.xml
  def show
    @news_blast = NewsBlast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news_blast }
    end
  end

  # GET /news_blasts/new
  # GET /news_blasts/new.xml
  def new
    if current_user.admin == false
    #if !current_user?(User.find(1))
      flash[:error] = "You must be logged in to use this feature."
      redirect_to users_path
      return
    end
    
    
    
    @news_blast = NewsBlast.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @news_blast }
    end
  end

  # GET /news_blasts/1/edit
  def edit
    @news_blast = NewsBlast.find(params[:id])
  end

  # POST /news_blasts
  # POST /news_blasts.xml
  def create
    @news_blast = NewsBlast.new(params[:news_blast])
    
    @news_blast.content = []
  
    params[:dyn].each do |n|
      index = n[0].to_i
      val = n[1]

      #next if val == ""

      #@news_blast.content << val

      @news_blast.content = val if index == 0
      @news_blast.content1 = val if index == 1
      @news_blast.content2 = val if index == 2
      @news_blast.content3 = val if index == 3
      @news_blast.content4 = val if index == 4
      @news_blast.content5 = val if index == 5
      @news_blast.content6 = val if index == 6
      @news_blast.content7 = val if index == 7

    end


    respond_to do |format|
      if @news_blast.save
        #format.html { redirect_to(@news_blast, :notice => 'News blast was successfully created.') }
        format.html { redirect_to(root_url, :notice => 'News blast was successfully created.') }
        format.xml  { render :xml => @news_blast, :status => :created, :location => @news_blast }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @news_blast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /news_blasts/1
  # PUT /news_blasts/1.xml
  def update
    @news_blast = NewsBlast.find(params[:id])

    respond_to do |format|
      if @news_blast.update_attributes(params[:news_blast])
        format.html { redirect_to(@news_blast, :notice => 'News blast was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @news_blast.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /news_blasts/1
  # DELETE /news_blasts/1.xml
  def destroy
    @news_blast = NewsBlast.find(params[:id])
    @news_blast.destroy

    respond_to do |format|
      format.html { redirect_to(news_blasts_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/news_blasts_helper.rb
module NewsBlastsHelper
end

app/views/news_blasts/_form.html.erb
<%= form_for(@news_blast) do |f| %>
  <% if @news_blast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_blast.errors.count, "error") %> prohibited this news_blast from being saved:</h2>

      <ul>
      <% @news_blast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %> 
  </div>
  <div class="field">
    <%= f.label :headline %><br />
    <%= f.text_field :headline %>
  </div>
  
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content, :id => 'dyn_0', :name => 'dyn[0]' %>
    
    <span class="more-items">
	  <a id="add-item-enabled" href="#add-item" onclick="additems();">more <span class="plus">+</span></a>
	</span>
	  
	<span class="less-items">
	  <a id="rem-item-enabled" href="#rem-item" onclick="remitems();">delete <span class="plus">-</span></a>
	</span>
  </div>
  
  <%= hidden_field_tag :content %>
  
  
  
  
  
  <div id="inputBottom"></div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_blasts/edit.html.erb
<h1>Editing news_blast</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_blast %> |
<%= link_to 'Back', news_blasts_path %>

app/views/news_blasts/index.html.erb
<h1>Listing news_blasts</h1>

<table>
  <tr>
    <th>Headline</th>
    <th>Content</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news_blasts.each do |news_blast| %>
  <tr>
    <td><%= news_blast.headline %></td>
    <td><%= news_blast.content %></td>
    <td><%= news_blast.date %></td>
    <td><%= link_to 'Show', news_blast %></td>
    <td><%= link_to 'Edit', edit_news_blast_path(news_blast) %></td>
    <td><%= link_to 'Destroy', news_blast, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News blast', new_news_blast_path %>

app/views/news_blasts/new.html.erb
<h1>New news_blast</h1>

<%= render 'form' %>

<%= link_to 'Back', news_blasts_path %>

app/views/news_blasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Headline:</b>
  <%= @news_blast.headline %>
</p>

<p>
  <b>Content:</b>
  <%= @news_blast.content %>
</p>

<p>
  <b>Date:</b>
  <%= @news_blast.date %>
</p>


<%= link_to 'Edit', edit_news_blast_path(@news_blast) %> |
<%= link_to 'Back', news_blasts_path %>