config/routes.rb
Xpd3::Application.routes.draw do
  
  resources :external_accounts

  resources :suppliers

  resources :ipfixes

  get "pages/directions"

  resources :cmdlines

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  root :to => 'pages#home'
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]  #qualifieing it like this means '/sessions/1' doesn't work, neither does '/sessions/1/edit'
  resources :relationships, :only => [:create, :destroy]
  resources :people, :only => [:create, :destroy, :index]
  
  resources :news_blasts
  
  match '/manage', :to => 'pages#manage'
  match '/about', :to => 'pages#about'
  match '/gallery', :to => 'pages#gallery'
  match '/specials', :to => 'pages#specials'
  match '/products', :to => 'pages#products'
  match '/news', :to => 'pages#news'
  match '/directions', :to => 'pages#directions'
  
  match "/brendan", :to => 'pages#brendan'
  
  match '/template', :to => 'pages#template'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/employees/new', :to => 'employees#new'
  
  resources :employees

end

app/models/cmdline.rb
class Cmdline < ActiveRecord::Base
end

app/controllers/cmdlines_controller.rb
class CmdlinesController < ApplicationController
  # GET /cmdlines
  # GET /cmdlines.xml
  def index
    @cmdlines = Cmdline.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cmdlines }
    end
  end

  # GET /cmdlines/1
  # GET /cmdlines/1.xml
  def show
    @cmdline = Cmdline.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cmdline }
    end
  end

  # GET /cmdlines/new
  # GET /cmdlines/new.xml
  def new
    @cmdline = Cmdline.new
    
    
    
    respond_to do |format|
      #format.html # new.html.erb
      format.html do
        render :xml => @cmdline
      end
        
      format.xml  { render :xml => @cmdline }
    end
  end

  # GET /cmdlines/1/edit
  def edit
    @cmdline = Cmdline.find(params[:id])
  end

  # POST /cmdlines
  # POST /cmdlines.xml
  def create
    @cmdline = Cmdline.new(params[:cmdline])
    
    case @cmdline[:cmd]
    when "HEY"
      resp = "it was 'HEY'"
    when "ls"
      resp = `ls config`
    else
      resp = "unknown command"
    end

    respond_to do |format|
      if @cmdline.save
        #format.html { redirect_to(@cmdline, :notice => 'Cmdline was successfully created.') }
        format.html { render :xml => @cmdline, :status => :created, :location => @cmdline }
        format.js { render :inline => resp }
        format.xml  { render :xml => @cmdline, :status => :created, :location => @cmdline }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cmdline.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cmdlines/1
  # PUT /cmdlines/1.xml
  def update
    @cmdline = Cmdline.find(params[:id])

    respond_to do |format|
      if @cmdline.update_attributes(params[:cmdline])
        format.html { redirect_to(@cmdline, :notice => 'Cmdline was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cmdline.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cmdlines/1
  # DELETE /cmdlines/1.xml
  def destroy
    @cmdline = Cmdline.find(params[:id])
    @cmdline.destroy

    respond_to do |format|
      format.html { redirect_to(cmdlines_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/cmdlines_helper.rb
module CmdlinesHelper
end

app/views/cmdlines/_form.html.erb
<style>
.cmdline input{
	width:200px
}
</style>


<%# form for command line...  Comand window is above...%>
<%= form_for(@cmdline) do |f| %>
  <% if @cmdline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cmdline.errors.count, "error") %> prohibited this cmdline from being saved:</h2>

      <ul>
      <% @cmdline.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="cmdline">
    <%= f.label :cmd %><br />
    <%= f.text_field :cmd %>
  </div>
  <div class="field">
    <%= f.label :response %><br />
    <%= f.text_field :response %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cmdlines/create.js.erb
alert('ajax works');

app/views/cmdlines/edit.html.erb
<h1>Editing cmdline</h1>

<%= render 'form' %>

<%= link_to 'Show', @cmdline %> |
<%= link_to 'Back', cmdlines_path %>

app/views/cmdlines/index.html.erb
<h1>Listing cmdlines</h1>

<table>
  <tr>
    <th>Cmd</th>
    <th>Response</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cmdlines.each do |cmdline| %>
  <tr>
    <td><%= cmdline.cmd %></td>
    <td><%= cmdline.response %></td>
    <td><%= link_to 'Show', cmdline %></td>
    <td><%= link_to 'Edit', edit_cmdline_path(cmdline) %></td>
    <td><%= link_to 'Destroy', cmdline, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cmdline', new_cmdline_path %>

app/views/cmdlines/new.html.erb
<h1>Cmd Line</h1>

<%= render 'form' %>

<%# link_to 'Back', cmdlines_path %>

app/views/cmdlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cmd:</b>
  <%= @cmdline.cmd %>
</p>

<p>
  <b>Response:</b>
  <%= @cmdline.response %>
</p>


<%= link_to 'Edit', edit_cmdline_path(@cmdline) %> |
<%= link_to 'Back', cmdlines_path %>