config/routes.rb
Xpd3::Application.routes.draw do
  
  resources :external_accounts

  resources :suppliers

  resources :ipfixes

  get "pages/directions"

  resources :cmdlines

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  root :to => 'pages#home'
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]  #qualifieing it like this means '/sessions/1' doesn't work, neither does '/sessions/1/edit'
  resources :relationships, :only => [:create, :destroy]
  resources :people, :only => [:create, :destroy, :index]
  
  resources :news_blasts
  
  match '/manage', :to => 'pages#manage'
  match '/about', :to => 'pages#about'
  match '/gallery', :to => 'pages#gallery'
  match '/specials', :to => 'pages#specials'
  match '/products', :to => 'pages#products'
  match '/news', :to => 'pages#news'
  match '/directions', :to => 'pages#directions'
  
  match "/brendan", :to => 'pages#brendan'
  
  match '/template', :to => 'pages#template'
  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/employees/new', :to => 'employees#new'
  
  resources :employees

end

app/models/address.rb
class Address < ActiveRecord::Base
  #belongs_to_and_has_many :persons     # we need has many since one household will have multiple people in it and they will likely link to the same addresses...???
  belongs_to :user
  
  attr_accessible :name, :state, :city, :zipcode, :address1, :address2
end

app/models/cmdline.rb
class Cmdline < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :email, :position_title, :dob, :origi_ndate, :employeeid
  belongs_to :user
end

app/models/external_account.rb
class ExternalAccount < ActiveRecord::Base
end

app/models/ipfix.rb
class Ipfix < ActiveRecord::Base
  attr_accessible :host, :ip
  
  validates :host, :uniqueness => true
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :content
  belongs_to :Userz
end

app/models/news_blast.rb
class NewsBlast < ActiveRecord::Base
  attr_accessible :date, :headline, :content
  
  validates_presence_of :date, :headline, :content
  #serialize :content
end

app/models/person.rb
class Person < ActiveRecord::Base  #rename this model to customer...
  belongs_to :user
  
  #has_many :addresses #
  
  attr_accessible :first_name, :last_name, :email
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id
  
  belongs_to :follower, :class_name => "User"  # tell rails to check within the "User" class, instead of the "Follower" class
  belongs_to :followed, :class_name => "User"  # points to User.follower_id

  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :password, :password_confirmation, :employee
  
  
  has_many :persons
  has_many :addresses
  
  has_one :employee, :dependent => :destroy
  
  
  
  has_many :relationships, :foreign_key => "follower_id", # override the foriegn key default, "relationship_id" 
                           :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed  # override to use "followed_id"
  
  
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  
  
  
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  #validates :name, :presence => true, :length   => { :maximum => 50 }
  
  validates :email, :presence => true, :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
  
  validates :password, :presence     => true,
                     :confirmation => true,
                     :length       => { :within => 6..40 }

  before_save :encrypt_password
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  
  def feed
    ## This is preliminary. See Chapter 12 for the full implementation.
    # Micropost.where("user_id = ?", id)
    Micropost.from_users_followed_by(self)
  end
  
  private
    
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate
  
  
  def home
    @news_blast = NewsBlast.last
    @user = current_user
  end

  def about
  end

  def gallery
  end

  def specials
  end

  def products
  end

  def news
  end
  
  def directions
  end
  
  
  def manage
    @employee = Employee.new
  end
  
  def template
  end
  
  def brendan
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  

   def client_browser_name
      user_agent = request.env['HTTP_USER_AGENT'].downcase
    if user_agent =~ /msie 8/i
      "ie8"
    elsif user_agent =~ /msie 7/i
      "ie7"
    elsif user_agent =~ /msie 6/i
      "ie6"
    elsif user_agent =~ /konqueror/i
      "konqueror"
    elsif user_agent =~ /gecko/i
      "mozilla"
    elsif user_agent =~ /opera/i
      "opera"
    elsif user_agent =~ /applewebkit/i
      "safari"
    else
      "unknown"
    end
  end

end

app/helpers/cmdlines_helper.rb
module CmdlinesHelper
end

app/helpers/ipfixes_helper.rb
module IpfixesHelper
end

app/helpers/news_blasts_helper.rb
module NewsBlastsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    #session[:user_id] = @user.id
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end  
  
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)       # removes the cookie from their computer
    self.current_user = nil               # 
  end

  def current_user?(user)       # checks if the current_user is the user supplied
    user == current_user
  end
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    clear_return_to
  end
  
  private
  
    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end
    
    def store_location
      session[:return_to] = request.fullpath
    end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.email,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/controls/_partners_slideup.html.erb
<% user_agent = client_browser_name %>

<% if user_agent == "ie8" or user_agent == "ie7" %>
	
		<h2 id="partners-header">Product Suppliers</h2>
			<div class="slide-up-boxes" style="padding-bottom:9px;width:295px;">
				<div id="ben" class="pbox"  style="width: 281px;height: 60px;overflow: hidden;" tag="paint">
					<img src="/images/partners-slideup/ben-slideup-mockup.jpg" width="281" height="126" alt="Benjamin Moore"/>
				</div>
				
				<div id="hun" class="pbox"  style="width: 281px;height: 60px;overflow: hidden;" tag="window treatments">
					<img src="/images/partners-slideup/hunt-slideup.jpg" width="281" height="126" alt="Hunter Douglas"/>
				</div>
				
				<div id="cam" class="pbox"  style="width: 281px;height: 60px;overflow: hidden;" tag="counter tops">
					<img src="/images/partners-slideup/partners-cambria.png" width="281" height="126" alt="Benjamin Moore"/>
				</div>
				
				<div id="fin" class="pbox"  style="width: 281px;height: 60px;overflow: hidden;" tag="paint">
					<img src="/images/partners-slideup/partners-finepaints.png" width="281" height="126" alt="Benjamin Moore"/>
				</div>
				
				<div id="sil" class="pbox"  style="width: 281px;height: 60px;overflow: hidden;" tag="tile">
					<img src="/images/partners-slideup/partners-silestone.png" width="281" height="126" alt="Benjamin Moore"/>
				</div>
				
				
				<div id="mag" class="pbox"  style="width: 281px;height: 60px;overflow: hidden;" tag="wood floor">
					<img src="/images/partners-slideup/partners-magnus.png" width="281" height="126" alt="Benjamin Moore"/>
				</div>
		
		


	</div>
		
<!--
	<div id="upgradeBrowser">
		<h1> Old Browser Detected </h1>
		<p>This is not an advertisement.  We (xpd) have detected that you are using <%= user_agent %> which does not support all the features that contemporary websites are designed for.  
		   Have you considered updating your browser?  Below is a list of modern browsers which may enhance your online shopping experience.</p>  
		<p style="padding-top:5px;"> --IT@excelsiorcarpetone.com</p>
		<ul>
			<li><a href="http://www.google.com/chrome/">Chrome</a> - Easiest setup</li>
			<li><a href="http://www.mozilla.com/en-US/firefox/fx/">Fire Fox</a> - Most extendable</li>
			<li><a href="http://www.microsoft.com/IE9">IE 9</a> - Most integrated (but more tedious to upgrade to and less feature rich)</li>
		</ul>
	</div>
-->

<% else %>



	<h2 id="partners-header">Product Suppliers</h2>
	<section class="slide-up-boxes">
		
		<div class="pbox">
			<a id="ben" href="#http://www.benjaminmoore.com/en-us/for-your-home/benjamin-moore-us-product-catalog" tag="paint">
				<div id="top" alt="Benjamin Moore"></div>
				<div id="bottom" alt="These guys do paint"></div>
			</a>
		</div>
		
		
		<div class="pbox">
			<a id="hun" href="#http://www.hunterdouglas.com/pdf/We_Make_Green_Beautiful.pdf" tag="window treatments">
				<div id="top" alt="Hunter Douglas"></div>
				<div id="bottom" alt="Blinds, etc."></div>	
			</a>
		</div>
		
		<div class="pbox">
			<a id="cam" href="#" tag="counter tops">
				<div id="top" alt="Cambria"></div>
				<div id="bottom" alt="Luxiury counter tops"></div>	
			</a>
		</div>
			
	
		<div class="pbox">
			<a id="fin" href="#" tag="paint">
				<div id="top" alt="Fine Paints of Europe"></div>
				<div id="bottom" alt="These guys do fine paint"></div>	
			</a>
		</div>
	
		<div class="pbox">	
			<a id="sil" href="#" tag="tile">
				<div id="top" alt="Silestone"></div>
				<div id="bottom" alt="Tile"></div>	
			</a>
		</div>
			
			
		<div class="pbox">
			<a id="mag" href="#" tag="wood floor">
				<div id="top" alt="Magnus Anderson"></div>
				<div id="bottom" alt="Wood floors"></div>
			</a>
		</div>
<!--			
		<a href="#">
			<div id="top" alt="DuPont Corian"></div>
			<div id="bottom" alt="Quartz Tile and Countertop"></div>	
		</a>
		
		
		<a href="http://www.hunterdouglas.com/pdf/We_Make_Green_Beautiful.pdf">
			<div id="top" alt="Graham Paint"></div>
			<div id="bottom" alt="These guys do paint"></div>
		</a>
		
		
		<a href="#">
			<div id="top" alt="Graham Paint"></div>
			<div id="bottom" alt="These guys do paint"></div>
		</a>
-->
	</section>
	
<% end %>



<script>

	function changeParagraph(element,cont)
	{
		if (element.hasClass("hilite")) {return;}
	      
	      // Change the lovely paragraph to be about benjamin moore
	      $(".pbox").removeClass("hilite");   
	      
	      
	      if (element.hasClass('pbox'))    // ie
	      {
	      	element.addClass("hilite");    
	      }
	      else                             // good browsers
	      {
	      	element.parent().addClass("hilite");
	      }
	      
	      
	      $("#lovely-description").slideUp('slow',
	      	function (){
	      		$("#lovely-description p").replaceWith("<p>" + cont + "</p>");
	      		$("#lovely-description").slideDown();
	      });
	}
	

    $("#ben").click(function () {
      //var content = "Benjamin Moore is the premier paint manufacturer in the USA.  They offer progressive zero VOC paints, as well as high performance paints you would expect from a paint manufacturer.  We have 3 color displays to shop from as well as a multitude of fan decks completing the Benjamin Moore collection.";
      var content = "Benjamin Moore has been dreaming in color since 1883.  At the forefront of product innovation, with a commitment to research and development unrivaled; striving to provide paint with the most minimal impact possible on the environment.  To deliver that paint with the newest in technology.  A commitment to color inspires an ongoing search for the perfect hues, the ones that lead our customers to claim: \"that's the color I want.\"";
      changeParagraph($(this),content);
    });
     
    $("#ben").dblclick(function () { 
	  // spawn pdf download
    });
    
    $("#hun").click(function () { 
      var content = "Hunter Douglas is a manufacturer of quality window treatments such as blinds, shutters, etc.";
      
      changeParagraph($(this),content);
    });

    
    $("#cam").click(function () { 
      var content = "Cambria is a great stone surface manufacturer.  They are partnered with Benjamin moore and offer professionally coordinated pain-countertop combinations.";
      
      changeParagraph($(this),content);
    });
    

    $("#fin").click(function () { 
      var content = "Fine Paints of Europe are the highest grade paint we offer.  If you're working on a project and need the absolute highest grade materials possible, you need look no further.  Give us a call or stop in to see us about this paint.  With this paint, we offer deliveries.";
      
      changeParagraph($(this),content);
    });

    
    
    $("#sil").click(function () { 
      var content = "Silestone is another of the great countertop and tile manufacturers we supply from.  We keep several Silestone displays on floor two.";
      
      changeParagraph($(this),content);
    });
    

    
    $("#mag").click(function () { 
      var content = "We are proud to be the owners of a Magnus Anderson dustless floor resurfacing unit.  DUSTLESS!  This no hassle solutions is the perfect thing for a quick, woodfloor resurfacing.";
      
      changeParagraph($(this),content);
    });
</script>

app/views/layouts/_flash.html.erb
<% if flash.length > 0 %>

  <div id="page-wrap">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>

<% end %>

app/views/layouts/_footer.html.erb
    <!-- BOTTOM ROW -->
<div id="page-wrap">
	
<!-- 	<p class="copyrightInfo"> copyright 2011 Excelsior Carpet One Paint &amp; Design Center</p>  -->	
	<div id="banner-bottom">
	<center> <script src="http://diadz.com/a/2120/8/2119.js" type="text/javascript"></script> </center>
	</div>
	
</div>


app/views/layouts/_header.html.erb
<div id="page-wrap" > 
	<div id="cool-banner">
	
		<div id="banner-left">
			<!-- Title -->	
			<div id="title">
				<img src="/ExImages/ECOtrans.png" alt="ECOtrans" width="511" height="64" />
			</div>
			
		</div>
		
		<img width="151" height="64" align="left" src="/ExImages/address.png">
		
		<div>
			<img width="143" height="34" src="/ExImages/hrs.png">
			<img width="224" height="92" alt="map" src="/ExImages/map.png">
		</div>
		
		<div id="spacer" style="clear:left"> </div>
		
		
		<!-- Karastan banner top -->
		<!--
		<div id="kara">
			<a style="display:block; float:left;" href="http://excelsior-paint-and-design---carpet-one.salesreact.com/p/55-karastan-promotion" target="_blank">
			<img src="/ExImages/410x84.gif" alt="Karastan" width="410" height="84"/></a>
		</div>
		-->
		
		
		<!-- Third Col  (I cheated with this one and used absolute positioning)-->
		<!--
		<div id="dir">
			<img src="/ExImages/dirSingle.jpg" width="271" height="168" alt="map" />
		</div>
		-->

		<div id="spacer"> </div>
	</div>
</div>


		

app/views/layouts/_navigation.html.erb
<div id="nav-side">
	
	<div>
		<a href="/">
			<img id="brand" src="/images/epdMainLgo.png"/>
		</a>
	</div>
	
	<div id="teal"></div>
	<div id="black-brand-img"></div>

	<ul id="menu">
		<li class="<%= "highlighted" if params[:action] == "home" %>"> <a href='/'> Home </a></li>
		<li class="<%= "highlighted" if params[:action] == "about" %>"><a href="/about">About Us</a></li>
		<li class="<%= "highlighted" if params[:action] == "gallery" %>"><a href="/gallery">Gallery</a></li>
		<li class="<%= "highlighted" if params[:action] == "specials" %>"><a href="/specials">Specials</a></li>
		<li class="<%= "highlighted" if params[:action] == "products" %>"><a href="/products" title="Products and Services" target="_self">Products</a></li>
		<li class="<%= "highlighted" if params[:action] == "news" %>"><a href="/news">News</a></li>
		<li class="<%= "highlighted" if params[:action] == "directions" %>"><a href="/directions">Directions</a></li>
		<% if signed_in? %>
                  <div id="accountNav">
                    <li id="myaccount" class="<%= "highlighted" if params[:action] == "show" %>"><a href="<%= user_path(current_user) %>">My Account</a></li>

                    <%# link_to user_path(current_user), user_path(current_user) %>
                    <li><%= link_to ">Sign out", signout_path, :method => :delete, :id => "signout" %> </li>
                  </div>
		<% end %>
	</ul>
	

	<div id="directions">
		<ul class="infoz">
			<li>701 Highway 7</li>
			<li>Excelsior MN 55331</li>
	    	<li>phone: 952.474.0162</li>
			<li>fax: 952.474.0162</li>
		</ul>
	</div>


	<div id="hours">
		<ul class="infoz">
			<li><b>Hours:</b> M-F 7:30-6:30;</li>
			<li>SAT 9-5; SUN 11-4</li>
		</ul>
	</div>
</div> <!-- /nav-side -->

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>Xpd3</title>

	<meta name="Description" content="Excelsior carpet one paint and design center supplies hunter douglas benjamin moore fine paints of europe" /> 
	<meta name="Keywords" content="excelsior, carpet one, color center, benjamin moore, paint, design, hunter douglas, cambria, excelsior carpet one, excelsior minnesota, 55331 excelsior carpet one, minnesota" /> 

	<%= csrf_meta_tag %>
	
	<%# javascript_include_tag 'jquery-1.6.2.min.js'%>
	<%= javascript_include_tag 'users_form' %>
	<%# javascript_include_tag :defaults %>
	<script type="text/javascript" src="/javascripts/jquery-1.6.2.min.js"></script>
	
	<script type="text/javascript" src="/javascripts/partners-grid.js"></script>
	
	
	<link href='http://fonts.googleapis.com/css?family=Questrial' rel='stylesheet' type='text/css'>
	<link type=text/css rel='stylesheet' href='/stylesheets/m.css'>
	<link type=text/css rel='stylesheet' href='/stylesheets/partners-grid.css'>
	

</head>
<body>
	<div class="page-wrap">

		<%# render 'layouts/header' %>
		<%= render 'layouts/navigation' %>
		<%= render 'layouts/flash', :flash => flash %>
		
		<div id="content">
			<%= yield %>
		</div>
	</div>

<%= render 'layouts/footer'%>

<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/_emp_form.html.erb
<%= form_for(@employee, :url => { :action => "create", :controller => "employees" } ) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label 'user', 'email', 'User Login email (user must have created account already)' %><br />
    <%= text_field(:user, :email) %>
  </div>
  <div class="field">
    <%= f.label :employeeid, 'Employee ID (workpro)' %><br />
    <%= f.text_field :employeeid %>
  </div>
  <div class="field">
    <%= f.label :position_title %><br />
    <%= f.text_field :position_title %>
  </div>
  <div class="field">
    <%= f.label 'Date of Birth' %><br />
    <%= f.text_field :dob %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_news_blasts.html.erb
<% if !@news_blast.nil? %>

<div id="news-blast" style="text-align:center; border-width:thin; border-style:solid; ">
	<div id="nb-title"><p><b>NEWS BLAST</b></p> </div>
	<div id="nb-headline"><%= @news_blast.headline%></div>
	<div id="nb-date"><b>- <%= @news_blast.date.strftime("%b %e") %> -</b> </div>
        <p><%= @news_blast.content %></p>

        <% if @news_blast.content1 != nil%>
          <br/>
          <p><%= @news_blast.content1 %></p>
        <% end %>

        <% if @news_blast.content2 != nil %>
          <br/>
          <p><%= @news_blast.content2 %></p>
        <% end %>
        <% if @news_blast.content3 != nil%>
          <br/>
          <p><%= @news_blast.content3 %></p>
        <% end %>
        <% if @news_blast.content4 != nil%>
          <br/>
          <p><%= @news_blast.content4 %></p>
        <% end %>
        <% if @news_blast.content5 != nil%>
          <br/>
          <p><%= @news_blast.content5 %></p>
        <% end %>
        <% if @news_blast.content6 != nil%>
          <br/>
          <p><%= @news_blast.content6 %></p>
        <% end %>
        <% if @news_blast.content7 != nil%>
          <br/>
          <p><%= @news_blast.content7 %></p>
        <% end %>

	<%# render :partial => 'shared/news_blast_item', :collection => @news_blast.content, :spacer_template => 'shared/spacer_part' %>  <%# auto iterates since you specify a collection, and puts in spacer between each element%>
</div>

<% end %>

app/views/pages/_products_offered.html.erb

	<script>
  $('#content').css('background', "#a2b3c1");
</script>
	
	
	<h1>Products and services include:</h1> 
	
	<p>FLOORING</p> 
	<ul> 
	  <li>Carpet</li> 
	  <li>TIle for floors and wall</li> 
	  <li>Solid wood</li> 
	  <li>Engineered wood</li> 
	  <li>Laminate</li> 
	  <li>Vinyl</li> 
	  <li>Magnus Anderson Dustless Sanding for wood floors </li> 
	</ul> 
	<p>WINDOW TREATMENTS</p> 
	<ul> 
	  <li>Hunter Douglas blinds</li> 
	  <li>Custom window treatments</li> 
	</ul> 
	<p>CABINETRY</p> 
	<ul> 
	  <li>Semi-custom cabinets </li> 
	  <li>Custom cabinets</li> 
	</ul> 
	<p>COUNTERTOPS</p> 
	<ul> 
	  <li>Granite</li> 
	  <li>Cambria countertops </li> 
	</ul> 
	<p>PAINT 
	</p> 
	<ul> 
	  <li>Benjamin Moore</li> 
	  <li>Fine Paint of Europe</li> 
	  <li>Graham</li> 
	</ul> 
	<p>and design services to tie your selections together, making your house your home.</p> 


app/views/pages/about.html.erb
<script>
  $('#content').css('background', "#e0e25e");
</script>



<div id="about-div">
	<h1><em>
		History
	</em></h1> 
	
	<h1>Offering more than just paint.</h1> 
	<p>Mr. Stans had a dream to open his own store on Water Street in downtown Excelsior selling paint, stain and wallpaper. He called his establishment  "The Color Center" and began serving the first of  three generations of clients.</span></p> 
	
	<p>The Color Center moved down the block to aquire more space in order to offer tile, carpet and dustless sanding. In 2006 needing even more space to showcase its ever increasing offerings, the store  moved to its current location, 701 Highway 7.</span></p> 
	
	<p>In August  2010, Carolyn Manhatton became the current owner. Now the establishment is called Excelsior   Paint & Design. When asked about the amount of moving in the company's history Carolyn says,&quot;The only place we are moving is up, meaning that we are focusing on our showrooms upstairs. We are lucky to have that space. . . there is a constant rotation of products both upstairs and downstairs.&quot;</span></p> 
	<p> Carolyn and her staff strive to maintain a level of quality and personal service that sets Excelsior Paint & Design apart.</span></p> 
	
	<%= render 'pages/products_offered'%>
</div>

app/views/pages/brendan.html.erb
I know what a wraith is!!
<br />
Hacked by Brendan!

<br />

The sky is falling!
<br/>
BANG!

app/views/pages/products.html.erb
<div id="page-wrap">
<%= render 'pages/products_offered'%>
</div>

app/views/pages/template.html.erb
PUT YOUR CONTENT HERE 

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="microposts">
      <%= pluralize(current_user.microposts.count, "micropost") %>
    </span>
  </a>
</div>